src/scss/main.scss

In n-ui, this was relying on another module to import o-overlay. Silly.

Missing overlay dependency

---

src/js/navigation.js

Fixes an issue where if the cloned nav item contains a tooltip, that was being cloned as well.
🐿 v2.9.0

Republishing nav item - only clone the link inside target element, not all children

---

src/js/navigation.js

When a nav container wasn't found, we were getting errors that prevented the rest of the JavaScript from running.
Have yet to figure out why this has all of a sudden become a problem though.

Being more defensive when finding a container for a nav item

---

src/js/republishing.js

During a refactor, some function calls hadn't been updated to remove some parameters, causing some issues when trying to trigger the modal for downloading Spanish content.

Fix spanish modal

---

.circleci/config.yml

This is a Bower component so it shouldn't be published to npm.

Remove `publish` job and `build-test-publish` workflow

---

src/js/config.js
src/js/modal-download.js

- adds a disclaimer to the download modal when the translations component is present on the page.
🐿 v2.10.3

[FT Labs] Translations disclaimer

---

src/js/navigation.js

Fixes #57 
Looks like a complete re-write, but basically it's just 
- moving existing code around a lot
- using `document.createElement` instead of `Node.cloneNode`
- creating the user-nav if it isn't present
Not great, as I don't really like all this dynamically creating elements in JS stuff (means styles/classes etc need to be kept updated in both in HTML and JS), but hopefully it's a slight improvement. Anyway, it means we can go ahead with the AB test referenced in #57 (I have tested it works locally)
🐿 v2.12.4

Ensure the republishing button gets added even if menu isn't there

---

src/js/modal-download.js

When `next-video-page` was migrated from `n-ui` to `dotcom-page-kit`, it inadvertently broke video download in syndication.
Once it was migrated, `o-viewport` was no longer being imported correctly and it caused the `n-syndication` to error before `USER_DATA` (necessary for video downloads) was set.
What changed from `n-ui` to `dotcom-page-kit`? With `n-ui` all code is transpiled to use the CommonJS module format and a plugin is used to check for a default export. If it comes across
one, as it does with `o-viewport`, it injects this:
```
exports.default = {listenTo, ...};
module.exports = exports.default;
```
This allowed `o-viewport` to be imported like this:
```
import {listenTo} from 'o-viewport';
listenTo();
```
`dotcom-page-kit` doesn't do this which is why `listenTo` from …

Fix video download bug in syndication

---

src/js/data-store.js
src/js/util.js

This excludes subnav elements from the array of elements sent to the syndication service and prevents the `/syndication/resolve` controller from being called if there are no syndicatable items on the page
In n-ui builds, the myFT subnav elements contain a `data-id` property. These are being mistakenly picked up by the current logic in n-syndication which uses `data-id` to create a list of syndicatable elements. 
This PR excludes subnav elements from the list above. 
It also prevents the syndication service from being called on a page if this list is empty because the [next-syndication-api](https://github.com/Financial-Times/next-syndication-api/blob/master/server/controllers/resolve.js#L26-L33) will throw an error if it receives an empty list.

Exclude subnav elements from the syndication request call 🐿 v2.12.5

---

src/js/data-store.js

Fixes the implementation in https://github.com/Financial-Times/n-syndication/pull/64 which tries to prevent a call to the syndication service from being made if there are no syndicatable elements on the page. 
Checking `itemsIDs.length` rather than `options.body.length` will correctly return 0 if there are no syndicatable items are found on the page.
[Illuminating explanation](https://github.com/Financial-Times/n-syndication/pull/64/files#r365920142) from @i-like-robots

fixes empty items check before the resolve syndication call 🐿 v2.12.5

---

.circleci/config.yml
package.json

I am upgrading the Node version of `next-session-client` to Node v12 (the current LTS version) in this [PR](https://github.com/Financial-Times/next-session-client/pull/52).
`next-session-client` is consumed by this app, and so it would make sense for everything to be aligned on the same Node version, and so this PR updates this app's Node version to v12.

Upgrade Node version -> v12

---

README.md

Wiki has a bit more info about Syndication and isn't the most obvious place to look, so people on OpsCops might struggle to find the info they need.

Added link to Wiki

---

package.json

When `bower link`ing from this component to `next-front-page` and then running `make build` (on `next-front-page`) I encountered this error:
Which presents itself again in the client-side console:
An investigation suggested that I install `babel-runtime` as a dev dependency, which has resolved the issue and enabled me to run `next-front-page` locally whilst `bower link`ing to a local instance of `n-syndication`.
- [GitHub wojtekmaj/react-pdf - Issues: "Module not found: Error: Can't resolve 'babel-runtime/regenerator'"](https://github.com/wojtekmaj/react-pdf/issues/310#issuecomment-463425172).
- [npm: @babel/runtime](https://www.npmjs.com/package/@babel/runtime).
- [Babel: @babel/runtime](https://babeljs.io/docs/en/next/babel-runtime.html).

Add @babel/runtime dev dependency

---

src/js/iconify.js
src/scss/main.scss

Content Innovation is in the process of updating all `next-article` toppers to use `o-topper`. This involves updating all class names so `o-topper` can apply the correct styles.
`n-syndication` relies on `topper__headline` to exist on the page which won't be the case when we move to `o-topper`. This PR updates the class name to `o-topper__headline`. I've confirmed it all works by running the component locally with `next-article`.
See https://github.com/Financial-Times/next-article/pull/3934
Incident page: https://response.ftops.tech/incident/697

CI-223 Update topper headline class names

---

src/js/index.js
src/js/messages.js
src/js/modal-download.js
test/src/js/messages.spec.js

Fixes check condition typo of  `allowed.rich_article` to  `allowed.rich_articles` as per the property returned by next-syndication-api
Updates logic for when “WORD” isn’t a default download format, 
Shows message when user has rich article licence, the content(article) has graphics, and users download format isn’t word

ACC-544 rich_articles not rich article

---

src/scss/main.scss

A fix to ensure that the syndication icons have a consistent alignment with its' sibling inline elements. 
Currently we have a few overrides to try an ensure there is a fixed value for the `vertical-align` rule however seems to be a symptom of `oIconsContent(...)` resetting the base icon style rules. This fix uses the `$include-base-styles: false` option that removes these base icon style rules removing the need to override the `vertical-align` rule for different variations. This fix also adds the `vertical-align: middle` rule to any sibling of `.n-syndication-icon` to make sure the alignment between these inline elements is consistent.
Closes #82 as this will remove the duplicated vertical-align overrides to create one consistent (🤞 ) style.
Here is some screen recordings of the new …

NOPS-619: Fix syndication icons alignment

---

README.md

The "Develop with a next app" and "Deployment" sections have instructions that no longer work. This PR updates these to either mention that it is planned to be rewritten or to give the correct details.

Update README with current developing and deploying instructions

---

README.md
bower.json
jest.config.js
package.json
scripts/fromBowerToNpm.js
webpack.config.js

This is very similar to PR https://github.com/Financial-Times/n-messaging-client/pull/360
Adding an option to install n-syndication lib through npm only. This is needed for the projects that no longer use bower

CON-903 Make library npm-compatible

---

.circleci/config.yml
.github/settings.yml
README.md
package.json

**Description**
Following the branch name change, this PR handles associated chores as per https://github.com/Financial-Times/next/wiki/Migrating-apps-to-use-main-branch-(instead-of-master)
- upgrades n-gage
- updates CI yaml to use the new name
- updates new name in links
**Ticket**
https://financialtimes.atlassian.net/browse/ACC-1169
**We're bumping how many n-gage versions?!**
TOO MANY. But I think none of those changes affect this repo.
v8.0.0 - the package-lock.json change is opt in https://github.com/Financial-Times/n-gage/releases/tag/v8.0.0
v7.0.0 - is an upgrade to Node v12 https://github.com/Financial-Times/n-gage/releases/tag/v7.0.0
v6.0.0 - something to do with asset-hashes.json, action only needed if this file is present in the project

ACC-1169 main branch name change chores

---

src/js/iconify.js

This rule is used for beta homepage(next-discovery-pages)
This `js-teaser-headline` class is added to beta homepage by [this PR](https://github.com/Financial-Times/next-discovery-pages/pull/590)
[Jira ticket](https://financialtimes.atlassian.net/browse/CON-903)

Add new rule for icon insertion

---

bower.json
package.json

Updating origami components to their latest bower available version: https://origami.ft.com/blog/2021/07/01/origami-on-npm-and-how-to-migrate/#last-bower-releases
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1360)

ACC-1360 update bower components

---

src/js/modal-maintenance.js

change the maintenance text to make it more generic
https://financialtimes.atlassian.net/browse/ACC-1212

ACC-1212 Make syndication maintenance message more generic

---

.eslintrc.js
.gitignore
package-lock.json
package.json

We have a PR that is pushed without issues, but is failing on ci because it has spaces and not tabs. This repo didn't respond to `eslint . --ext .jsx,.js` - this PR fixes that. It also adds a config that relies on the next standard and a couple of npm scripts so that people can run `npm run lint-fix`.

sort out linting issues

---

.circleci/config.yml
package-lock.json
package.json

We're invited to embrace progress and enhance our estate by upgrading them to Node 18. This upgrade brings exciting improvements and features. 
This PR migrates the app to use node 18.
Our dedicated platform team has meticulously developed a migration script, which can be found [here](https://github.com/Financial-Times/platform-scripts/blob/main/upgrade-node-18/README.md)
[Ticket](https://financialtimes.atlassian.net/browse/ACC-2435)

chore: update to node 18

---

.circleci/config.yml

Whilst doing the toolkit migration to version 4, the tool-kit/publish-tag job got the filters.tags.only field removed. This possibly caused the publish job to not result in a new version being pushed to the npm registry. This is an attempt to fix that.
[JIRA](https://financialtimes.atlassian.net/browse/LIF-109)

LIF-109 Add filters to publish job

---

.circleci/config.yml

Whilst doing the toolkit migration to version 4, the some of the filters.tags.only fields got removed. This possibly caused the publish job to not result in a new version being pushed to the npm registry. This should now fully fix this.
[JIRA](https://financialtimes.atlassian.net/browse/LIF-109)

LIF-109 Add filters to build and test jobs
