src/js/index.js

Check that user exists before checking its properties

---

package.json
src/js/config.js
src/js/data-store.js
src/js/get-user-status.js
src/js/iconify.js
src/js/modal-download.js
src/js/republishing.js
src/js/util.js
src/scss/main.scss
webpack.config.js

Add support for package items

---

bower.json

No [breaking changes](https://github.com/Financial-Times/n-ui-foundations/issues/34#issuecomment-341787777) for this module

Bump n-ui-foundations to v3

---

.gitignore
package.json
src/js/config.js

We have a new component, n-topic-card, which has a different set of selectors.

Add topic card selectors

---

.gitignore
src/js/config.js
src/js/modal-download.js
src/scss/main.scss

🐿 v2.7.0
Adds styling to highlight where extra charges apply

highlight extra charge messaging

---

src/scss/main.scss

remove max-height on modal

---

src/js/redux.js

remove reference to syndicationDownloadMediaResource flag

---

src/js/index.js
src/js/redux.js

remove usage of syndicationRedux flag

---

src/js/navigation.js

update data-trackable for value used selectorInsertionPoint

---

README.md

@simonplend Hopefully this adds a bit more info. As a non user is there anything else you reckon should be added?
🐿 v2.9.0

add local development and deployment instructions

---

src/js/config.js
src/js/iconify.js
src/js/modal-download.js

Reduce areas where we are building selectors using vars

---

src/js/config.js

Adds warning style to translation disclaimer.
🐿 v2.10.3

[Update] adds warning style

---

bower.json
package.json
src/js/config.js
src/js/data-store.js
src/js/iconify.js
src/js/index.js
src/js/modal-download.js
src/js/republishing.js
src/js/util.js

Inline declarations in `config.js` to make code more readable
🐿 v2.12.3

OpsCops - Inline config

---

src/js/config.js

Remove trailing whitespace

---

src/js/config.js
src/js/iconify.js
src/js/index.js
src/js/modal-download.js
src/js/util.js

- Refactors the model-download code so that the `message` decision logic is in a separate shareable function in `./config.js`;
- Refactors model-download code to be clearer.
- Adds hidden message in iconify icons for accessibility.

ops cops / make less inaccessible

---

src/js/config.js
src/js/data-store.js
src/js/get-user-status.js
src/js/iconify.js
src/js/index.js
src/js/modal-download.js
src/js/navigation.js
src/js/republishing.js
src/js/util.js

fix linting errors

---

package.json
src/js/modal-download.js

Fix save button href (switch ternary order)

---

bower.json

Jira card: https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-84.
I have `bower link`ed this component and run locally on `next-front-page` and all looks good.

Upgrade n-ui-foundations 4.0.0-beta.2 -> ^6.0.0

---

README.md
bower.json
main.js
package.json
secret-squirrel.js
src/js/config.js
src/js/iconify.js
src/js/index.js
src/js/messages.js
src/js/modal-download.js
src/js/user-access.js
src/scss/main.scss
test/fixtures/items.json
test/fixtures/userProducts.js
test/fixtures/userStatus.json
test/src/js/config.spec.js
test/src/js/data-store.spec.js
test/src/js/index.spec.js
test/src/js/messages.spec.js
test/src/js/user-access.spec.js

Superceeds https://github.com/Financial-Times/n-syndication/pull/77

ACC-544 graphics download message box

---

bower.json
package.json
scripts/fromBowerToNpm.js

Add missing o-viewport for npm install

CON-903 Add o-viewport for npm install

---

bower.json
package-lock.json
package.json

Regenerating package-lock and keeping bower.json the same as previously for components that were already on their latest major version.

ACC-1360 Fix origami update

---

README.md

Remove duplicated documentation
[ACC-2285](https://financialtimes.atlassian.net/browse/ACC-2285)
[ACC-2285]: https://financialtimes.atlassian.net/browse/ACC-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-2285: add link to rotate keys

---

jest.config.js
src/js/data-store.js
src/js/iconify.js
src/js/modal-download.js
src/js/modal-maintenance.js
src/js/navigation.js
src/js/util.js
test/src/js/data-store.spec.js
test/src/js/get-user-status.spec.js
test/src/js/iconify.spec.js
test/src/js/messages.spec.js
test/src/js/modal-download.spec.js
test/src/js/modal-maintenance.spec.js
test/src/js/navigation.spec.js
test/src/js/user-access.spec.js
test/src/js/util.spec.js

This pull request aims to enhance the unit test coverage for the n-syndication module by addressing gaps in the existing tests. The identified files that require improved coverage are shared in the tickets. By expanding the unit test suite, we can ensure better code quality, increase reliability, and facilitate future development and maintenance.
Key Changes:
- Added unit tests for the identified files within the n-syndication module
- Implemented test cases to cover previously untested scenarios and edge cases
- Enhanced the test suite to improve overall coverage and code quality
[Jira Ticket](https://financialtimes.atlassian.net/browse/ACC-2373)
some useful links on spying in jest
https://medium.com/@DavideRama/mock-spy-exported-functions-within-a-single-module-in-jest-cdf2b61af642 …

ACC-2373-Test coverage improvement

---

CODEOWNERS

This PR updates the CODEOWNERS file to reflect its new ownership.
[LIF-2: Admin for setting up Lifecycle team's resources](https://financialtimes.atlassian.net/jira/software/c/projects/LIF/boards/2009/?selectedIssue=LIF-2)
N/A

Update CODEOWNERS to @financial-times/cp-customer-lifecycle

---

package-lock.json
package.json
src/js/data-store.js
src/js/get-user-status.js
src/js/iconify.js
src/js/index.js
src/js/modal-download.js
src/js/modal-maintenance.js
src/js/navigation.js
src/js/republishing.js
src/js/util.js
src/scss/main.scss
test/src/js/get-user-status.spec.js
test/src/js/iconify.spec.js
test/src/js/modal-download.spec.js
test/src/js/modal-maintenance.spec.js
test/src/js/navigation.spec.js

Migrate package from origami o2 to origami o3
[Jira ticket](https://financialtimes.atlassian.net/browse/CPO3-43)

O3 migration
